steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    args: ['test']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/prueba-tecnica/pruebatecnica-imagen', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/prueba-tecnica/pruebatecnica-imagen']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'pruebatecnica-servicio'
      - '--image'
      - 'gcr.io/$PROJECT_ID/prueba-tecnica/pruebatecnica-imagen'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--add-cloudsql-instances'
      - 'my-nodejs-app-438001:us-central1:prueba-tecnica'
      - '--set-env-vars'
      - 'CLOUD_SQL_CONNECTION_NAME=my-nodejs-app-438001:us-central1:prueba-tecnica,DB_USER=postgres,DB_PASS=12345,DB_NAME=pruebaTecnica,ACCESS_TOKEN_SECRET=A$@cVxM5^ZWcS!nH#9H$&a3#N%YP@mQ8,REFRESH_TOKEN_SECRET=f&8MZq^@1U!mL#4JWkCvX3*Vz%Yf@J^P'
      - '--allow-unauthenticated'


timeout: '1200s'
