version: '3'
services:
  app:
    build: .
    environment:
      - NODE_ENV=development
      - PORT=8080
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    deploy:
      replicas: 5
  nginx:
      image: nginx:latest
      ports:
        - "80:80" 
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf  
      depends_on:
        - app  